---
- name: Quick webserver install and config
  hosts: localhost
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root
  tasks:
    # Install Apache Web Server
    - name: Install apache webserver
      ansible.builtin.package:
        name: apache2  # Change httpd to apache2 for Ubuntu/Debian
        state: present
        use: apt  # Specify the package manager as apt

    # Ensure Apache is Running
    - name: Start and enable apache service
      ansible.builtin.service:
        name: apache2  # Use apache2 for Ubuntu/Debian
        state: started
        enabled: true

    # Configure index.html
    - name: Write a simple index.html file
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        line: "Hello World!"
        create: true

